name: Retrain model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check code compilation
        run: |
          python -m compileall .

  image-delivery:
    name: "Docker Image Delivery"
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "testing"
    steps:
      - uses: ./python_setup_template.yml
        with:
          job: common-setup-python
      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_DOCKER_CONFIGURATION }}
      - name: Build Docker image
        run: |
          docker build ./ -t ${{ secrets.IMAGE_URI }}
      - name: Push Docker image to repository
        run: |
          docker push ${{ secrets.IMAGE_URI }}

  train:
    name: "Train"
    needs: [build, image-delivery]
    runs-on: ubuntu-latest
    environment:
      name: "testing"
    steps:
      - uses: ./python_setup_template.yml
        with:
          job: common-setup-python
      - name: Execute Python script for model retraining
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          CONTAINER_URI: ${{ secrets.CONTAINER_URI }}
          VERTEX_AI_JOB: ${{ secrets.VERTEX_AI_JOB_NAME }}
          MACHINE_TYPE: ${{secrets.VERTEX_AI_MACHINE_TYPE}}
        run: python pipeline/train-model.py --bucket $BUCKET_NAME --container_uri $CONTAINER_URI --vertex_ai_job $VERTEX_AI_JOB --machine_type $MACHINE_TYPE

  deploy:
    name: "Deploy"
    needs: [build, image-delivery, train]
    runs-on: ubuntu-latest
    environment:
      name: "testing"
    steps:
      - uses: ./python_setup_template.yml
        with:
          job: common-setup-python
      - name: Execute Python script for model deployment
        run: python pipeline/deploy-model.py --bucket_name ${{ secrets.BUCKET_NAME }} --serving_container_image_uri ${{ secrets.SERVING_CONTAINER_URI }} --project_id ${{ secrets.PROJECT_ID }}
